import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { mkdir, mkdtemp, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import test from "node:test";
import { buildUiApp, inspectUiApp } from "../scripts/ui-app-builder.mjs";

test("large self-contained message UI and card JSON survive build and round-trip intact", async function largeStressCase() {
  const root = await mkdtemp(path.join(tmpdir(), "rp-large-artifact-")); const app = path.join(root, "app"); await mkdir(path.join(app, "styles"), { recursive: true }); await mkdir(path.join(app, "scripts"), { recursive: true }); await mkdir(path.join(app, "mock"), { recursive: true });
  await writeFile(path.join(app, "ui-app.yaml"), `schema_version: 1.0.0\nui_app:\n  id: stress-surface\n  surface: zero_layer\n  experience_level: super_heavy\n  output_mode: message_surface\n  entry_html: index.html\n  styles: [styles/app.css]\n  scripts: [scripts/app.js]\n  fragments: []\n  mock_state: mock/state.json\n  preview_output: dist/preview.html\n  script_wrapper: none\n  output: dist/runtime.html\n`);
  await writeFile(path.join(app, "index.html"), `<head><meta name="viewport" content="width=device-width"><!-- RP_UI_STYLES --></head><body><main id="app"></main><script type="module">window.__module_booted__=true</script><!-- RP_UI_SCRIPTS --></body>`);
  const cssUnit = `.panel{display:grid;grid-template-columns:repeat(12,minmax(0,1fr));background:linear-gradient(135deg,#08131d,#173247);color:#eefaff;border:1px solid #315568;padding:12px}\n`; await writeFile(path.join(app, "styles", "app.css"), cssUnit.repeat(4200)); await writeFile(path.join(app, "scripts", "app.js"), `document.querySelector('#app').textContent='大型前端制品';`); await writeFile(path.join(app, "mock", "state.json"), JSON.stringify({ 世界: { 地区: "长文本".repeat(5000) } }));
  const built = await buildUiApp(path.join(app, "ui-app.yaml")); assert.ok(built.bytes > 600_000); assert.match(built.html, /<script type="module">/); const inspected = await inspectUiApp(path.join(app, "ui-app.yaml"), path.join(app, "dist", "runtime.html")); assert.equal(inspected.outputMatches, true);
  const entries = Array.from({ length: 422 }, (_, index) => ({ id: index + 1, keys: [], secondary_keys: [], comment: `资料条目${index + 1}`, content: `条目正文${index + 1}\n${"设定".repeat(1500)}`, constant: false, selective: false, insertion_order: index, enabled: false, position: "before_char", extensions: {} }));
  const card = { spec: "chara_card_v3", spec_version: "3.0", data: { name: "压力测试包", description: "完整 RP 包入口", personality: "", scenario: "", first_mes: "<压力测试/>", mes_example: "", creator_notes: "制品往返测试".repeat(100000), system_prompt: "", post_history_instructions: "", alternate_greetings: [], tags: [], creator: "rp-card-studio", character_version: "1.0", character_book: { name: "压力测试世界书", description: "", scan_depth: null, token_budget: null, recursive_scanning: false, extensions: {}, entries }, extensions: { regex_scripts: [{ id: "d9be1e83-a232-47ce-a8af-62187db69715", scriptName: "大型前端", findRegex: "/<压力测试\\s*\\/>/g", replaceString: built.html, trimStrings: [], placement: [2], disabled: false, markdownOnly: true, promptOnly: false, runOnEdit: true, substituteRegex: 0, minDepth: null, maxDepth: null }] } } };
  const serialized = JSON.stringify(card); assert.ok(Buffer.byteLength(serialized) > 2_000_000); const hash = createHash("sha256").update(serialized).digest("hex"); const roundTrip = JSON.stringify(JSON.parse(serialized)); assert.equal(createHash("sha256").update(roundTrip).digest("hex"), hash); assert.equal(JSON.parse(roundTrip).data.extensions.regex_scripts[0].replaceString, built.html); assert.equal(JSON.parse(roundTrip).data.character_book.entries.length, 422);
});
