import assert from "node:assert/strict";
import { mkdtemp, writeFile, rm } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import { validateRuntimeSources } from "../scripts/rp-card-runtime.mjs";

const html = `<!doctype html><html><head><meta name="viewport" content="width=device-width"><style>.root{color:#fff}@media(max-width:600px){.root{display:block}}</style></head><body><textarea id="fog-raw" hidden>$1</textarea><main class="root"><nav data-tab="overview">总览</nav><nav data-tab="people">人物</nav><section id="view-overview">状态</section><section id="view-people">人物</section><button type="button">行动</button><script>var host=window.parent;</script><div class="search detail fallback">空态</div><script>try{var raw=document.getElementById("fog-raw").value; console.log(raw)}catch(e){console.error(e)}</script></main></body></html>`;

function entry(id, content) { return { id, display_name: id, source: { kind: "inline", content }, enabled: true, activation: { mode: "constant", primary_keys: [], secondary_keys: [], selective: false, logic: "any", case_sensitive: false, match_whole_words: false }, insertion: { position: "at_depth", order: 100, depth: 0, role: "system" }, probability: 100, scan_depth: null, recursion: { prevent_incoming: true, prevent_outgoing: true, delay_until_recursion: false }, recipient: "shared", visibility: "model", ignore_budget: true, token_budget: null, fallback: "block" }; }
function sources(file, broken = false) { const marker = "<雾港状态><地点>...</地点></雾港状态>"; const surface = { id: "fog", name: "雾港状态", marker, file: path.basename(file), render_route: "regex_replace", data_route: "message_capture", message_contract: { kind: "structured_xml", transport: "regex_capture", outer_tag: "雾港状态", record_syntax: "bracket_pipe", capture_group: 1, payload_mount: "hidden_textarea", partial_stream: "tolerant", fixture_file: "fixture.xml", empty_policy: "显示空态" }, emission: { producer: "model_output", cadence: "every_assistant_message", source_ref: "wb_fog", evidence: [] } }; const regex = { id: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa", script_name: "雾港状态显示", find_regex: "/<雾港状态>([\\s\\S]*?)<\\/雾港状态>/g", replace_string: html, placement: [2], disabled: false, markdown_only: true, prompt_only: false }; const status_ui = { enabled: true, authoring_mode: "direct_html", experience_level: "light", data_density: "unknown", theme_direction: "雾港", device_priority: "equal", surfaces: [surface], data_sources: [], host_interactions: [], experience_evidence: { baseline: { navigation: ["导航"], data_views: ["状态"], information_tools: ["搜索"], host_actions: ["行动"], feedback_states: ["空态"], responsive_checks: ["窄屏"], theme_features: ["雾港"], data_binding: ["消息快照"] }, level_advancements: {}, primary_play_surface: false }, lifecycle_checks: [], runtime: "not_run" }; const asm = { worldbook_manifest: { entries: [entry("wb_fog", "每次回复末尾必须输出以下 XML 状态块：" + marker)] }, runtime_manifest: { mode: "authored", regex_scripts: [regex], tavern_helper_scripts: [], extension_fields: {} } }; return { assembly: [{ value: asm }], ui: [{ value: { schema_version: "2.0.0", status: "locked", status_ui, source_refs: [] } }], prompts: [], mvu: [], ejs: [], world: [], characters: [], systems: [], scenes: [], positioning: [] }; }

test("message capture route validates a complete non-MVU chain", async (t) => { const root = await mkdtemp(path.join(os.tmpdir(), "rp-nonvar-")); t.after(() => rm(root, { recursive: true, force: true })); await writeFile(path.join(root, "status.html"), html); await writeFile(path.join(root, "fixture.xml"), "<雾港状态><地点>[名称|雾港]</地点></雾港状态>"); const report = await validateRuntimeSources({ project: { features: { status_ui: true } }, sources: sources(path.join(root, "status.html")), projectRoot: root }); assert.deepEqual(report.issues, []); });

test("message capture route rejects a missing safe payload mount", async (t) => { const root = await mkdtemp(path.join(os.tmpdir(), "rp-nonvar-broken-")); t.after(() => rm(root, { recursive: true, force: true })); await writeFile(path.join(root, "status.html"), html.replace("$1", "静态数据")); await writeFile(path.join(root, "fixture.xml"), "<雾港状态><地点>[名称|雾港]</地点></雾港状态>"); const report = await validateRuntimeSources({ project: { features: { status_ui: true } }, sources: sources(path.join(root, "status.html")), projectRoot: root }); assert.ok(report.issues.some((item) => item.rule === "ui.message_injection")); });
